### ISSUE TITLE
Npc portal master in Stormwind City but no Transfer point🐛 [Bug]

### ISSUE THREAD

**Issue by qqwqqwe** [alexkulya/pandaria_5.4.8#106]
Npc portal master in Stormwind City but no Transfer point

**Comment by alexkulya** [comment]
@qqwqqwe Describe the problem in more detail. Maybe you have a non-standard NPC with a different Entry and, accordingly, a scriptname is not attached to it. Or the Gossip flag is not specified.

**Comment by qqwqqwe** [comment]
Portal Master is a teleporter NPC 
It has 130+ teleports including all zones in wow.

**Comment by qqwqqwe** [comment]
https://rochet2.github.io/Portal-Master.html

**Comment by qqwqqwe** [comment]
ok，this is ues Portal Master for 3.35 and no import  success yet by myself.
