### ISSUE TITLE
Quest bug The Amphitheater of Anguish: Magnataur! 

### ISSUE THREAD

**Issue by Ramys** [alexkulya/pandaria_5.4.8#11]
Bug - The Amphitheater of Anguish: Magnataur! Link : http://www.wowhead.com/quest=12933
Npcs does not start and has no target. 

Quest chain is
http://www.wowhead.com/quest=12932
1.The Champion's Call! http://www.wowhead.com/quest=12974
2.The Amphitheater of Anguish: Yggdras! http://www.wowhead.com/quest=12932
3.The Amphitheater of Anguish: Magnataur! http://www.wowhead.com/quest=12933
4.The Amphitheater of Anguish: From Beyond! http://www.wowhead.com/quest=12934
5.The Amphitheater of Anguish: Tuskarrmageddon! http://www.wowhead.com/quest=12935
6.The Amphitheater of Anguish: Korrak the Bloodrager! http://www.wowhead.com/quest=12936
7.The Champion of Anguish http://www.wowhead.com/quest=12948

**Comment by alexkulya** [comment]
The entire quest chain now works seamlessly.
https://github.com/alexkulya/pandaria_5.4.8/commit/8c7de3f9f247c0ddf2e93907d47c3bb69999d394

**Comment by Ramys** [comment]
Still not starting npc , quest The Amphitheater of Anguish: Magnataur! http://www.wowhead.com/quest=12933

https://ibb.co/Tm0M1jh
https://ibb.co/NVwvpRs

**Comment by alexkulya** [comment]
@Ramys 
https://recordit.co/HHSriLNGWj

**Comment by Ramys** [comment]
> @Ramys https://recordit.co/HHSriLNGWj

even applying it still doesn't work for me.

very strange.
@alexkulya

**Comment by alexkulya** [comment]
@Ramys
Perhaps this is due to the fact that you are using an irrelevant world database. Please try to do all these actions with the current database (dir: sql / base / world.7z + applying all updates from dir: updates). At the moment, these errors are absent in the debug log.

**Comment by Ramys** [comment]
I'm using this db.
https://github.com/alexkulya/pandaria_5.4.8/blob/master/sql/base/world.7z
I was applying to each update and I noticed the error.
Every time I apply these two updates, a lot breaks on the server. (https://github.com/alexkulya/pandaria_5.4.8/blob/master/sql/updates/world/2021_12_21_01_world_sai_Full_548.sql
https://github.com/alexkulya/pandaria_5.4.8/blob/master/sql/updates/world/2021_12_21_02_world_sai_creature_template_names.sql)
I ncluding the quest.  The Amphitheater of Anguish: Magnataur! http://www.wowhead.com/quest=12933 and  The Amphitheater of Anguish: Korrak the Bloodrager! http://www.wowhead.com/quest=12936

**Comment by alexkulya** [comment]
https://github.com/alexkulya/pandaria_5.4.8/commit/279288fad9c9acfeb4688b9ea933c8e95d9cfdfe

Added the latest up-to-date database. Now there should be no such mistakes. Please, put and write about the results.
@Ramys

**Comment by Ramys** [comment]
> [279288f](https://github.com/alexkulya/pandaria_5.4.8/commit/279288fad9c9acfeb4688b9ea933c8e95d9cfdfe)
> 
> Added the latest up-to-date database. Now there should be no such mistakes. Please, put and write about the results. @Ramys

Now everything works perfectly!
@alexkulya
