### ISSUE TITLE
🐛 [Bug]After a chest or other item is picked up, the spawned box or other items can no longer be used. Indicates that the item is being used

### ISSUE THREAD

**Issue by ddk2001** [alexkulya/pandaria_5.4.8#122]
After a chest or other item is picked up, the spawned box or other items can no longer be used. Indicates that the item is being used。

![RUR@`X%8MQ6FRNIZ6 @HMOD](https://github.com/alexkulya/pandaria_5.4.8/assets/29648605/765235cc-a184-4ab5-a502-e86ad650faeb)

**Comment by alexkulya** [comment]
I noticed this problem. We will fix it.

**Comment by ddk2001** [comment]
Thank. I really like this version of pandaria.Hopefully this source code is getting better and better

**Comment by ddk2001** [comment]
At the same time, can it strengthen the anticheat, such as accelerating or flying back to the same place?

**Comment by alexkulya** [comment]
> After a chest or other item is picked up, the spawned box or other items can no longer be used. Indicates that the item is being used。
> 
> ![RUR@`X%8MQ6FRNIZ6 @HMOD](https://private-user-images.githubusercontent.com/29648605/307677070-765235cc-a184-4ab5-a502-e86ad650faeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjA3MjksIm5iZiI6MTcwOTEyMDQyOSwicGF0aCI6Ii8yOTY0ODYwNS8zMDc2NzcwNzAtNzY1MjM1Y2MtYTE4NC00YWI1LWE1MDItZTg2YWQ2NTBmYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExNDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NTA5MjY1NzdjNzM2MjVjZTRkNTkxMmI1MGFjMGQ0N2NkZWY4YjczNjkxMTAzODEyMjllMmViOTFhZjI0NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WR8C5fhz-GpltGpMjZ_dkez9HN3es_yztC-B5IdNU-E)

Fixed it. Will be included in a future update.

**Comment by ddk2001** [comment]
The new address of SkyFire548 is: https://codeberg.org/ProjectSkyfire/SkyFire_548

**Comment by ddk2001** [comment]
Are you being dragged to the battlefield in Ukraine? It's been a long time since I heard back

**Comment by ReyDonovan** [comment]
no one is being dragged, we are already returning

**Comment by ReyDonovan** [comment]
It's a funny bug that I don't see myself, I need to look at what could have broken it

**Comment by ddk2001** [comment]
That's pretty good.

**Comment by ddk2001** [comment]
Debug mode also can't see what the reason is

**Comment by ddk2001** [comment]
Where did Alexkulya go, I haven't seen him for a long time. I thought he went to the Ukrainian battlefield

**Comment by ReyDonovan** [comment]
@ddk2001 I completely repaired the Pandaren chain and went through it in my core, I didn’t encounter such a problem

**Comment by ddk2001** [comment]
Is there a link to git, I'll pull it and see. @ReyDonovan

**Comment by ReyDonovan** [comment]
@ddk2001 https://github.com/ReyDonovan/TrinityPandaCore
in fact, our kernels have the same root)

**Comment by ddk2001** [comment]
Thanks, the kernel is basically a fix and change based on Skyfire. I'll pull and compile it.

**Comment by ddk2001** [comment]
I'm trying to add your source code  ELUNA
