### ISSUE TITLE
worldsever cannt run

### ISSUE THREAD

**Issue by huaijiuwow** [alexkulya/pandaria_5.4.8#123]
serverlog is play
Validating spell scripts...
Spell `348` Effect `Index: EFFECT_2 Target: 6` of script `spell_warl_havoc_target_selector` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `348` Effect `Index: Invalid Value Target: 6` of script `spell_warl_havoc_target_selector` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `1126` Effect `Index: EFFECT_0 Name: 3` of script `spell_dru_mark_of_the_wild_stats` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `1459` Effect `Index: EFFECT_0 Name: 3` of script `spell_mage_arcane_brilliance_stats` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `1490` Effect `Index: EFFECT_1 Target: 6` of script `spell_warl_havoc_target_selector` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `1490` Effect `Index: Invalid Value Target: 6` of script `spell_warl_havoc_target_selector` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed
Spell `6572` Effect `Index: EFFECT_2 Name: 30` of script `spell_warr_revenge_shield_slam` did not match dbc effect data - handler bound to hook `OnEffectHitTarget` of SpellScript won't be executed
Spell `6789` Effect `Index: EFFECT_2 Target: 6` of script `spell_warl_havoc_target_selector` did not match dbc effect data - handler bound to hook `OnObjectAreaTargetSelect` of SpellScript won't be executed

**Comment by ddk2001** [comment]
This should be the script missing, unfinished

**Comment by huaijiuwow** [comment]
> This should be the script missing, unfinished

Do you know how to solve this problem？is the world database error？

**Comment by alexkulya** [comment]
d438348
