### ISSUE TITLE
VS 2019 16.10 Compile Error

### ISSUE THREAD

**Issue by cooler-SAI** [alexkulya/pandaria_5.4.8#15]
У меня ошибка при компиляции(( есть идеи?

![image](https://user-images.githubusercontent.com/812439/149984780-486590a9-b81e-4dfa-8325-ebcad1e147a3.png)

**Comment by cooler-SAI** [comment]
ревизия последняя,
Win 11 x64

https://github.com/alexkulya/pandaria_5.4.8/commit/8ec4b6f2a186e0029b3a5a16e8f9c9e2cea2f591

**Comment by KinomiyaTakao** [comment]
Hi dude,
Cmake: the mysql sources part must be disabled   (delete the old compilation folder) I am using boost 1.64
` i compiled it without problems 😃 `

**Comment by alexkulya** [comment]
Now compile without errors

Microsoft Visual Studio Professional 2019 version 16.10.4
Boost 1.71.0

**Comment by cooler-SAI** [comment]
yeah! my bad! I use MySQL 8.0
