### ISSUE TITLE
dbc, maps, vmaps

### ISSUE THREAD

**Issue by ReyDonovan** [alexkulya/pandaria_5.4.8#16]
can anyone upload it to a file sharing site? I would be very grateful

**Comment by Ramys** [comment]
https://mega.nz/file/X1lWCY7Q#j0Lj1kPVdGsLae0s3FVUMkFf20vqYqfqE_CjlQGghT0

Repack , maps, vmaps and etc.

**Comment by ReyDonovan** [comment]
thx
