### ISSUE TITLE
Creatures Pandaria

### ISSUE THREAD

**Issue by Ramys** [alexkulya/pandaria_5.4.8#18]
Dead creatures and no attacks.

Creature 1 =  https://pt.wowhead.com/npc=59156/ef%C3%ADgie-mogu
Creature 2 = https://www.wowhead.com/npc=59157/granite-quilen
Creature 3 = https://www.wowhead.com/npc=60223/granite-quilen
Creature 4 = https://www.wowhead.com/npc=65816/granite-quilen
Creature 5 = https://www.wowhead.com/npc=58460/shao-tien-soul-render
Creature 6 = https://www.wowhead.com/npc=58412/shao-tien-marauder
Creature 7 = https://www.wowhead.com/npc=60225/shao-tien-marauder
Creature 8 = https://www.wowhead.com/npc=59158/subjugated-serpent
Creature 9 = https://www.wowhead.com/npc=65824/shao-tien-behemoth
Creature 10 = https://www.wowhead.com/npc=60225/shao-tien-marauder

**Comment by ReyDonovan** [comment]
see creature_addon and creature_template_addon

**Comment by cooler-SAI** [comment]
creature_template also have stunned flag

**Comment by cooler-SAI** [comment]
@ReyDonovan  PM me on Discord cooler-SAI#1526

**Comment by JadeCore** [comment]
this SkyFire
