### ISSUE TITLE
CrossFaction 

### ISSUE THREAD

**Issue by Fabiduarte** [alexkulya/pandaria_5.4.8#21]
Hello good afternoon, could you implement CrossFaction please?

**Comment by alexkulya** [comment]
@Fabiduarte 
You need to set up the configuration:
base 'auth' -> table 'config' -> category 'Battlegrounds' -> name 'Battleground.IgnoreFaction' set value to 1. Now when two alliance players register, one of them will be transferred to the horde. The only difference is that the character's racial model does not change.
