### ISSUE TITLE
Raid entrance terrace of endless spring(TOS)

### ISSUE THREAD

**Issue by vfedor32** [alexkulya/pandaria_5.4.8#23]
Hello, I started running core tests and noticed this problem, When trying to enter the terrace of endless spring(TOS) raid, the player receives an error message in all difficulty modes (10.10HM,25,25HM).If you turn on the GM, you can safely enter the dungeon

Screen-https://ibb.co/6nrCjwm
Screen from worldserver console-https://ibb.co/nzZd3CR

Thank you for your work!

**Comment by alexkulya** [comment]
Fixed.
