### ISSUE TITLE
Black Market Npc in Pandaria don't work

### ISSUE THREAD

**Issue by vfedor32** [alexkulya/pandaria_5.4.8#24]
Hello, thank you for the previous fix, I continue to test the core, and found another big problem.The NPC-62943 should open a black market window.Core don't have that script npc_madam_goya
Video with problem---https://youtu.be/wTwLp-WWW0Y
Thanks for your work!

**Comment by alexkulya** [comment]
@vfedor32
Make sure that the BlackMarket.Open parameter in the worldserver.conf file is set to 1, you are using an up-to-date world database.

See:
https://recordit.co/eVHWiQYFcO

**Comment by vfedor32** [comment]
Thanks!
