### ISSUE TITLE
Compile Error with Tools

### ISSUE THREAD

**Issue by StarlordDev** [alexkulya/pandaria_5.4.8#25]
Hello, apparently the project gives an error when compiling with tools

My configuration is:
* Windows 10 x 64 bit.
* Boost 1.72
* MySQL 5.7
* VisualStudio 19
* OpenSSL 1.1

* I have generated the project with TOOLS in CMAKE 3.21.2
* I have compiled in ReldWhitDebInfo x64

ERROR:
Error LNK1104 cannot open file 'libboost_date_time-vc142-mt-x64-1_72.lib'   mmaps_generator
C:build\src\tools\mmaps_generator\LINK

**Comment by alexkulya** [comment]
@StarlordDev
boost 1.71.0, MySQL 5.7.31, Microsoft Visual Studio Professional 2019
(Version 16.10.4), cmake 3.19.4-win64-x64.
My set of programs. Compilation without errors (With and without tools).

**Comment by Ramys** [comment]
@alexkulya
do you happen to have a solocraft script for that core?

**Comment by alexkulya** [comment]
@Ramys At the moment, there is no solocraft or scripts similar to it in the core.

**Comment by StarlordDev** [comment]
Hi, I have tried to change to your configuration but I keep getting the same error :(

**Comment by Ramys** [comment]
@StarlordDev , Did you change the boost version in the variables?

**Comment by StarlordDev** [comment]
Yes, I have modified the variables. I have downloaded Boost 1.71 but I have the same error 'cannot open file 'libboost_date_time-vc142-mt-x64-1_71.lib'' I don't know what I am doing wrong 😖 

Note:
* try to change boost to MSVC 12 but CMAKE fails.

**Comment by Ramys** [comment]
clean cmake project and use boost 1.70

**Comment by StarlordDev** [comment]
I have reinstalled everything but the error persists, I don't understand why it can't open libboost_date_time.

**Comment by Ramys** [comment]
cmake 3.19.4-win64-x64

**Comment by StarlordDev** [comment]
It still doesn't work, I'll be on the lookout in case someone has the same problem and manages to find a solution. Thanks

**Comment by Ramys** [comment]
Visual studio 17 , works for me..

**Comment by Ramys** [comment]
@StarlordDev 

Visual Studio 17 , please.

**Comment by alexkulya** [comment]
@StarlordDev
Why close the issue without solving it. I was at work so I couldn't answer you. In the cmake before starting the build, clear the folder with the old build, clear the cache, and before starting a new build, check that the boost path is set correctly. I have attached a screenshot of my boost paths.
![Screenshot_1](https://user-images.githubusercontent.com/7693165/152493049-3d4107d9-8ddd-49d8-a4cc-91aa21669ccd.png)

**Comment by Ramys** [comment]
if it clears cmake it will work.
@StarlordDev

**Comment by DevPrimeR** [comment]
Compile to Debug or Release or RelWithDebInfo?

**Comment by StarlordDev** [comment]
I think I have found the error. apparently mmaps_generator is not compatible with MSVC 14.2 I have managed to compile without tools using BOOST 1.72/171 without problems. I have tried to change BOOST with MSVC 14.1 but it seems that my compiler is not compatible and more errors are generated.

**Comment by Ramys** [comment]
I compile without maps..

**Comment by StarlordDev** [comment]
mapextractor.exe, vmap4assembler.exe and vmap4extractor.exe are working correctly, the one that has a compile error is mmaps_generator.exe

**Comment by Ramys** [comment]
dude, use the maps I sent... it's easier for you to extract everything again

**Comment by StarlordDev** [comment]
I already extracted them xD

**Comment by Ramys** [comment]
server to host a website, fusion or Blizzcms.

**Comment by StarlordDev** [comment]
can it be disabled? the project will only be for local use.

**Comment by alexkulya** [comment]
@StarlordDev Without a website, you can use everything locally. It is not worth disabling access or deleting the Fusion base, since there are balance data from the in-game store.

**Comment by alexkulya** [comment]
About extracting cards:
place all four extractors in the client directory, add the my attached *.bat file there and run it.
[simple_extractor.zip](https://github.com/alexkulya/pandaria_5.4.8/files/8007681/simple_extractor.zip)

**Comment by DevPrimeR** [comment]
Thanks, I have already extracted the maps, except for mmaps_generator.exe, which is where I have an error.

**Comment by StarlordDev** [comment]
Thanks, I've already extracted the maps. I close this Issue, although it is necessary to verify why mmaps_generator.exe has errors when compiling with MSVC 14.2
