### ISSUE TITLE
Error when compiling.

### ISSUE THREAD

**Issue by Ramys** [alexkulya/pandaria_5.4.8#29]
After the new fixes I came across these new errors when compiling.

https://ibb.co/tzh02ZD

Warning C4715 'spell_nalak_throw_spear::CheckCast': not all control paths return a value scripts pandaria_5.4.8\src\server\scripts\pandaria\zone_isle_of_thunder.cpp 4305

Warning C4060 switch statement does not contain any labels 'case' or 'default' scripts pandaria_5.4.8\src\server\scripts\Custom\protected_zone.cpp 25

Error C3861 'dtMathSqrtf': identifier not found game : pandaria_5.4.8\src\server\game\Movement\PathGenerator.cpp 152

Error C3861 'dtMathSqrtf': identifier not found game  :pandaria_5.4.8\src\server\game\Movement\PathGenerator.cpp 909

Warning C4715 'spell_warr_unbridled_wrath::spell_warr_unbridled_wrath_AuraScript::checkProc': not all control paths return a value scripts : pandaria_5.4.8\src\server\scripts\spells\spell_warrior.cpp 339

**Comment by alexkulya** [comment]
@Ramys Download the source code again and recompile. There were no changes in the files that appear in the errors.

**Comment by Ramys** [comment]
Ok..thks.
