### ISSUE TITLE
quest Not In the Face! ( panda )

### ISSUE THREAD

**Issue by remamakiller** [alexkulya/pandaria_5.4.8#32]
In the quest of the panda 29772 , [Not In the Face!] Ask Shu for help , it works perfectly , but in Wake Wugou , Shu does not cast the spell to wake up Wugou. and therefore , does not complete the quest and can not continue.

**Comment by KOOHS** [comment]
![WoWScrnShot_012322_190618](https://user-images.githubusercontent.com/24800063/155802081-cfe94516-9823-4d41-b704-42d0d6b9fa8e.jpg)

**Comment by KOOHS** [comment]
Tá ok eu fiz ela

**Comment by remamakiller** [comment]
Continue to complete it, you will see that shu does not wake up Wugou and does not complete it.

**Comment by davidwow1024** [comment]
only use 
UPDATE creature_template SET ScriptName='', AIname='SmartAI' WHERE entry=55477;

**Comment by remamakiller** [comment]
davidwow1024 , by placing this command, it remains the same
https://youtu.be/x3UKohGjbEs

**Comment by KOOHS** [comment]
I did it, it works, there's no bug, you're using k4s1pro/torghst

**Comment by KOOHS** [comment]
Use of alexkulya
