### ISSUE TITLE
worldserver can not run,FusionCMS is what?

### ISSUE THREAD

**Issue by huaijiuwow** [alexkulya/pandaria_5.4.8#34]
Using configuration file worldserver.conf.
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using ACE version: 7.0.0
Pandaria 5.4.8 Rev: 0 Release Hash: Archive (Win64, little-endian) (worldserver-daemon)
<Ctrl-C> to stop.

    ─╔═══╗╔═══╗╔═╗─╔╗╔═══╗╔═══╗╔═══╗╔══╗╔═══╗─                          
    ─║╔═╗║║╔═╗║║║╚╗║║╚╗╔╗║║╔═╗║║╔═╗║╚╣─╝║╔═╗║─                          
    ─║╚═╝║║║─║║║╔╗╚╝║─║║║║║║─║║║╚═╝║─║║─║║─║║─                          
    ─║╔══╝║╚═╝║║║╚╗║║─║║║║║╚═╝║║╔╗╔╝─║║─║╚═╝║─                          
    ─║║───║╔═╗║║║─║║║╔╝╚╝║║╔═╗║║║║╚╗╔╣─╗║╔═╗║─                          
    ─╚╝───╚╝─╚╝╚╝─╚═╝╚═══╝╚╝─╚╝╚╝╚═╝╚══╝╚╝─╚╝─                          
                                                                        
             ─╔═══╗───╔╗─╔╗────╔═══╗─                                   
             ─║╔══╝───║║─║║────║╔═╗║─                                   
             ─║╚══╗───║╚═╝║────║╚═╝║─                                   
             ─╚══╗║───╚══╗║────║╔═╗║─                                   
             ─╔══╝║──╔╗──║║─╔╗─║╚═╝║─                                   
             ─╚═══╝──╚╝──╚╝─╚╝─╚═══╝─                                   
                                                                        
                  PANDARIA 5.4.8                                        
                     Based on:                                          
                Project SkyFireEmu                                      
         <http://www.projectskyfire.org/> 
                            
FusionCMS database not specified in configuration file

**Comment by ReyDonovan** [comment]
[fusion_database.zip](https://github.com/alexkulya/pandaria_5.4.8/files/8152599/fusion_database.zip)

**Comment by alexkulya** [comment]
https://github.com/alexkulya/pandaria_5.4.8/blob/master/sql/base/fusion.sql
