### ISSUE TITLE
thunder island

### ISSUE THREAD

**Issue by remamakiller** [alexkulya/pandaria_5.4.8#35]
on thunder island, the pirate ship is missing and therefore the player hordes are left in the water.
![image](https://user-images.githubusercontent.com/8194404/156043326-20de9a01-8eb4-4e38-8721-063843eddbad.png)

**Comment by alexkulya** [comment]
I didn't see this problem myself. Perhaps someone will report a different result when testing. The Isle of Thunder needs some cosmetic repairs and some fixes, but overall it's passable.

**Comment by Garona0125** [comment]
Alliance can be transmitted to the ship.

**Comment by remamakiller** [comment]
The problem is with the horde ship.
As you can see in the image
