### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Ramys** [alexkulya/pandaria_5.4.8#4]
Severity Code Description Project File Line Status Suppression
Error C2039 'level': not a member of 'Guild' scripts pandaria_5.4.8\src\server\scripts\Commands\cs_guild.cpp 238

Severity Code Description Project File Line Status Suppression
Error LNK1104 cannot open file '..\scripts\Debug\scripts.lib' worldserver Panda\src\server\worldserver\LINK 1

**Comment by alexkulya** [comment]
Fixed.

**Comment by Ramys** [comment]
Perfect!
