### ISSUE TITLE
 Quest  [Road to greatness]

### ISSUE THREAD

**Issue by avirax94** [alexkulya/pandaria_5.4.8#41]
the mission at the moment of taking it the door an example disappears.
![image](https://user-images.githubusercontent.com/48683701/157375931-fda85f45-294a-47a4-9c48-4de450107e68.png)
there it is when I have the mission.
Now I don't have the mission
![image](https://user-images.githubusercontent.com/48683701/157376051-4d466419-7264-4b35-b240-be1b52b2aa8b.png)
quest name
[Road to greatness]
id quest
29792

**Comment by davidwow1024** [comment]
Hasla de nuevo y fíjate q tengas el world de acá completo por q esa funciona perfecto y no uses velocidad ni gm por que tiene sai y tienen q llegar los npc q te las abren y te acompañan hasta abajo

**Comment by KOOHS** [comment]
item=28209/old-whitebarks-pendant
quest=10166/whitebarks-memory   problem is quest item
