### ISSUE TITLE
darkened horror npc

### ISSUE THREAD

**Issue by avirax94** [alexkulya/pandaria_5.4.8#42]
npc 56007
darkened horror
he has a life of 1 with one hit we kill him he needs an update so that his normal life is established
![image](https://user-images.githubusercontent.com/48683701/157377771-cb626913-1816-494e-8402-633b9728d3d6.png)

**Comment by remamakiller** [comment]
fix npc
UPDATE creature_template SET health_mod = 272 WHERE entry =56007;
UPDATE creature_template SET health_mod = 318 WHERE entry =56008;

**Comment by kuramajssken001** [comment]
Well done, man. we should have paid attention to the repair of details, rather than other unimportant things.
