### ISSUE TITLE
dbc maps vmaps 

### ISSUE THREAD

**Issue by Dude100** [alexkulya/pandaria_5.4.8#45]
Can anyone upload it to a file sharing site thanks

**Comment by DevPrimeR** [comment]
Hello, the extractors of the project work correctly, you must have the full client to be able to extract them.
If not try downloading these:
https://github.com/alexkulya/pandaria_5.4.8/issues/16
Note: this data does not contain mmaps.

**Comment by Dude100** [comment]
thanks

**Comment by KOOHS** [comment]
https://mega.nz/file/26pExIiR#ILjCwRh-PJlCRK2_Z51qwtxGIKD9x5lh28NnWlM78XA

**Comment by KOOHS** [comment]
https://mega.nz/file/LipChIBB#Kzh_VOtf3kAUZJJ-0TQhvvYSAB-BvpJ910hgGypXffM

**Comment by KOOHS** [comment]
https://mega.nz/file/TyJlBbDY#k_mtM_dSuPNyiGtV-2gy0kz4ombZjwxj7IS0JIknKqs

**Comment by KOOHS** [comment]
https://mega.nz/file/qvgkSSKb#XHT7tnOcr9p5Snls8yBT67ZaIm3DFPOq9X0IXGL_6bk

**Comment by SkyFire** [comment]
@KOOHS Sharing links to copyrighted files publicly opens this project up to copyright infringement and they will take it down.

**Comment by KOOHS** [comment]
you are boring guy your core is trash não tá pra usar ele pra servidor privado

**Comment by SkyFire** [comment]
@KOOHS You don't have to be a dick. BTW my core is the base of this project. I was just pointing out the links to copyrighted content will get Blizzards attention and they will take it offline then you are shit out of luck.

**Comment by alexkulya** [comment]
@KOOHS Don't start a showdown here. @SkyFire absolutely right wrote, if you need to transfer something related to the kernel (extractors, repacks, etc.), it's better to do it through the discord group, or I will have to restrict access to the project only to a certain circle of people. And something else, as wrote above, and it was clear earlier, SkyFire is the core that is the base for this project and I will ask you to treat respectfully a person with the nickname @SkyFire. Thanks.

**Comment by KOOHS** [comment]
I just passed a link from the mega I found the person wanted the maps I don't know my dear @Skyfire's English he cursed me but it's ok sorry !!
