### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by Dude100** [alexkulya/pandaria_5.4.8#55]
Ubuntu 20 server: 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
after last update compile fail
https://pastebin.com/8MfGq3Mb

**Comment by kuramajssken001** [comment]
@Dude100  Debian9.9 try again.

**Comment by Err0r1** [comment]
Debian 9 is EOL! It's not recommended to use an OS that no longer receives (security) updates

**Comment by KOOHS** [comment]
Oi
