### ISSUE TITLE
Gameobject (GUID: 547289 Entry: 216666) not created: gameobject type GAMEOBJECT_TYPE_TRANSPORT cannot be manually created.

### ISSUE THREAD

**Issue by qqwqqwe** [alexkulya/pandaria_5.4.8#69]
Gameobject (GUID: 547289 Entry: 216666) not created: gameobject type GAMEOBJECT_TYPE_TRANSPORT cannot be manually created.

**Comment by fuzionproject** [comment]
can you let here the errors list from visual studio compilation? to can fix the problem
and adding sniff files

**Comment by qqwqqwe** [comment]
Error in world server

**Comment by SkyFire** [comment]
Just ignore it. It's the Darkmoon Carousel. It's not defined in the event table.

**Comment by qqwqqwe** [comment]
ok, thanks.
