### ISSUE TITLE
VS 2019, boost 1.70+

### ISSUE THREAD

**Issue by cooler-SAI** [alexkulya/pandaria_5.4.8#7]
Друже,можешь поднять до визуалки 2019? не хочу удалять ее и ставить 2017)

**Comment by Crandalius** [comment]
You need to use the same version as what's stated on the readme, I've compiled this with VS2019 and had no issues at all

**Comment by Ramys** [comment]
I have both installed on the pc normally.
I use both vs17 and vs19.

**Comment by alexkulya** [comment]
At the moment, it makes no sense to update the soft to the version above. Maybe later. May be.
