### ISSUE TITLE
🐛 [Bug] ticket system

### ISSUE THREAD

**Issue by shahinprophet** [alexkulya/pandaria_5.4.8#71]
ticket system  command .ticket viewid or name  not work

**Comment by alexkulya** [comment]
@shahinprophet You may be trying to use this command with insufficient access.

![Screenshot_1](https://user-images.githubusercontent.com/7693165/181728331-2a57bf17-00f0-4438-939f-e2fc76f70b48.png)
.

**Comment by davidwow1024** [comment]
crashe the system on values ​​that it does not recognize and the .pinfo
