### ISSUE TITLE
It's a Town-In-A-Box🐛 [Bug]

### ISSUE THREAD

**Issue by Steyfix** [alexkulya/pandaria_5.4.8#75]
## 🐛 Bug report

Quest Name: It's a Town-In-A-Box
Quest ID: 14245
Zone: Goblin

Small bug on this quest, I go up as the objective says on the stack of dinamite and press the gossip. This completes the quest well but when it explodes I am well propelled in the air but on the descent a parachute is normally present but it does not deploy and I die at the reception.

thank you

Client Version: 
- 5.4.8.18414

**Comment by davidwow1024** [comment]
fixed thank papakiller
