### ISSUE TITLE
quest 24958🐛 [Bug]

### ISSUE THREAD

**Issue by Steyfix** [alexkulya/pandaria_5.4.8#77]
quest: 24958
name: Volcanoth

encountered problem:

The item given with the quest does not work on the objective. Once killed the objective is accomplished but little concern to return the quest the npc in the plane is too high for the player and does not allow him to return the quest.

Client Version: 
  - 5.4.8.18414

**Comment by davidwow1024** [comment]
fixed

**Comment by Steyfix** [comment]
Good Thanks
