### ISSUE TITLE
quest 29663 The Lesson of the Balanced Rock🐛 [Bug]

### ISSUE THREAD

**Issue by Steyfix** [alexkulya/pandaria_5.4.8#78]
quest id: 29663
quest name: The Lesson of the Balanced Rock

encountered problem:

on this quest by climbing on the potos and when you want to engage in combat with the quest npc's you die afterwards and you don't have to free your spirit.
For this to work we must attack the NPCs on the ground.
conclusion: worry about immediate death on a combat engagement once on the potos.

  - 5.4.8.18414

**Comment by dbasset31** [comment]
hin i have this bug too, how i can fix it ? it's a bug sql or c++ ? when i have fix it, i make a pull request

**Comment by dbasset31** [comment]
i have find how resolv it : 

in database, add 109308 in spell1 and set 5 on mindmg and 10 to maxdmg to table creature_template for id 65468 and enjoy ;)

**Comment by Steyfix** [comment]
great thank you i will have to try it.
