### ISSUE TITLE
Bug commande npc add crash server🐛 [Bug]

### ISSUE THREAD

**Issue by Steyfix** [alexkulya/pandaria_5.4.8#81]
Hello, I am reporting a bug in the .npc add command which causes the server to crash immediately afterwards.
I place below the summary of the crash of my .log:

Pandaria 5.4.8Rev: 0  Hash: Archive (Unix, little-endian) (worldserver-daemon) ready...
Aura::_UnapplyForTarget, target:582693, caster:582693, spell:22766 was not found in owners application map!
ASSERTION FAILED: (false) at /root/MopCore/src/server/game/Spells/Auras/SpellAuras.cpp:749
In funtion: virtual void Aura::_UnapplyForTarget(Unit *, Unit *, AuraApplication *)
./worldserver(_ZN8UnitAura17_UnapplyForTargetEP4UnitS1_P15AuraApplication+0xf) [0x25afd6f]
./worldserver(_ZN4Unit12_UnapplyAuraERSt17_Rb_tree_iteratorISt4pairIKjP15AuraApplicationEE14AuraRemoveMode+0x823) [0x22c6c53]
./worldserver(_ZN4Unit21RemoveAllAurasOnDeathEv+0x76) [0x22c99f6]
./worldserver(_ZN4Unit13setDeathStateE10DeathState+0x185) [0x22e7ae5]
./worldserver(_ZN8Creature13setDeathStateE10DeathState+0xe) [0x215ed0e]
./worldserver(_ZN4Unit4KillEPS_bPK9SpellInfo+0x1b2b) [0x22b128b]
./worldserver(_ZN4Unit10DealDamageEPS_jPK11CleanDamage16DamageEffectType15SpellSchoolMaskPK9SpellInfob+0x1204) [0x22ad6d4]
./worldserver(_ZN18misc_commandscript19HandleDamageCommandEP11ChatHandlerPKc+0x378) [0x1e65988]
./worldserver(_ZN11ChatHandler21ExecuteCommandInTableERKSt6vectorI11ChatCommandSaIS1_EEPKcRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x368) [0x1ff2348]
./worldserver(_ZN11ChatHandler13ParseCommandsEPKc+0x11a) [0x1ff2cea]
./worldserver(_ZN12WorldSession23HandleMessagechatOpcodeER11WorldPacket+0x932) [0x26f4142]
./worldserver(_ZN12WorldSession6UpdateEjR12PacketFilter+0xaa2) [0x2574da2]
./worldserver(_ZN5World14UpdateSessionsEj+0x142) [0x2684e82]
./worldserver(_ZN5World6UpdateEj+0x4a6) [0x2682626]
./worldserver(_ZN13WorldRunnable3runEv+0x21f) [0x116e0cf]
./worldserver(_ZN9ACE_Based6Thread10ThreadTaskEPv+0xa) [0x274a00a]
/lib/libACE-6.4.5.so(_ZN21ACE_OS_Thread_Adapter6invokeEv+0xd6) [0x7f887a7d22f6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f887a2f0609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f8879ec7133]

ASSERTION FAILED: (itr->second == auraApp) at /root/MopCore/src/server/game/Spells/Auras/SpellAuras.cpp:753
In funtion: virtual void Aura::_UnapplyForTarget(Unit *, Unit *, AuraApplication *)
./worldserver(_ZN8UnitAura17_UnapplyForTargetEP4UnitS1_P15AuraApplication+0xf) [0x25afd6f]
./worldserver(_ZN4Unit12_UnapplyAuraERSt17_Rb_tree_iteratorISt4pairIKjP15AuraApplicationEE14AuraRemoveMode+0x823) [0x22c6c53]
./worldserver(_ZN4Unit21RemoveAllAurasOnDeathEv+0x76) [0x22c99f6]
./worldserver(_ZN4Unit13setDeathStateE10DeathState+0x185) [0x22e7ae5]
./worldserver(_ZN8Creature13setDeathStateE10DeathState+0xe) [0x215ed0e]
./worldserver(_ZN4Unit4KillEPS_bPK9SpellInfo+0x1b2b) [0x22b128b]
./worldserver(_ZN4Unit10DealDamageEPS_jPK11CleanDamage16DamageEffectType15SpellSchoolMaskPK9SpellInfob+0x1204) [0x22ad6d4]
./worldserver(_ZN18misc_commandscript19HandleDamageCommandEP11ChatHandlerPKc+0x378) [0x1e65988]
./worldserver(_ZN11ChatHandler21ExecuteCommandInTableERKSt6vectorI11ChatCommandSaIS1_EEPKcRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x368) [0x1ff2348]
./worldserver(_ZN11ChatHandler13ParseCommandsEPKc+0x11a) [0x1ff2cea]
./worldserver(_ZN12WorldSession23HandleMessagechatOpcodeER11WorldPacket+0x932) [0x26f4142]
./worldserver(_ZN12WorldSession6UpdateEjR12PacketFilter+0xaa2) [0x2574da2]
./worldserver(_ZN5World14UpdateSessionsEj+0x142) [0x2684e82]
./worldserver(_ZN5World6UpdateEj+0x4a6) [0x2682626]
./worldserver(_ZN13WorldRunnable3runEv+0x21f) [0x116e0cf]
./worldserver(_ZN9ACE_Based6Thread10ThreadTaskEPv+0xa) [0x274a00a]
/lib/libACE-6.4.5.so(_ZN21ACE_OS_Thread_Adapter6invokeEv+0xd6) [0x7f887a7d22f6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f887a2f0609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f8879ec7133]

Thanks for the help provided

  - 5.4.8.18414
-->
Client Version:

**Comment by alexkulya** [comment]
Checked commands: .npc add and .npc del - there is no server crash. Try updating the server and database to the latest version and try again and post the result.
