### ISSUE TITLE
Bug spell=69041 rocket-barrage

### ISSUE THREAD

**Issue by mlsantos1286** [alexkulya/pandaria_5.4.8#84]
The Goblin's Racial rocket-barrage Spell is not casting the Spell or Spell..it counts the Cooldown but the spell is not cast
https://www.wowhead.com/spell=69041/rocket-barrage
![215713-rocket-barrage-wowhead-now-as-a-racial](https://user-images.githubusercontent.com/60577217/207503385-00914be1-881c-4ced-a03d-2d056c743aec.jpg)

**Comment by alexkulya** [comment]
https://github.com/alexkulya/pandaria_5.4.8/commit/113edb625cfa494f84b0f137f9525c08c475e0fd
